// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ6geDKz7BE6FAYAK-UjGci0yKi3jMEIk',
    appId: '1:25021432919:web:bc09bdf459d5f7d19ccf12',
    messagingSenderId: '25021432919',
    projectId: 'elhwary-shop',
    authDomain: 'elhwary-shop.firebaseapp.com',
    storageBucket: 'elhwary-shop.firebasestorage.app',
    measurementId: 'G-Z8GTL7E5RB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDojFDaRmR9B1eou3CD85HDs6QwYhsyVvo',
    appId: '1:25021432919:android:0fc941f9e8c447a09ccf12',
    messagingSenderId: '25021432919',
    projectId: 'elhwary-shop',
    storageBucket: 'elhwary-shop.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA319RluhZYcnA_VMvFW7KFhZCvZB5tzXQ',
    appId: '1:25021432919:ios:9e00f6f3a16afb439ccf12',
    messagingSenderId: '25021432919',
    projectId: 'elhwary-shop',
    storageBucket: 'elhwary-shop.firebasestorage.app',
    iosBundleId: 'com.example.elhwar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA319RluhZYcnA_VMvFW7KFhZCvZB5tzXQ',
    appId: '1:25021432919:ios:9e00f6f3a16afb439ccf12',
    messagingSenderId: '25021432919',
    projectId: 'elhwary-shop',
    storageBucket: 'elhwary-shop.firebasestorage.app',
    iosBundleId: 'com.example.elhwar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZ6geDKz7BE6FAYAK-UjGci0yKi3jMEIk',
    appId: '1:25021432919:web:e6de022e72b6dcac9ccf12',
    messagingSenderId: '25021432919',
    projectId: 'elhwary-shop',
    authDomain: 'elhwary-shop.firebaseapp.com',
    storageBucket: 'elhwary-shop.firebasestorage.app',
    measurementId: 'G-XBWWV36EH9',
  );
}
